name: nakha
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+13

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Navigation & Routing
  go_router: ^17.0.1

  # Localization & Internationalization
  easy_localization: ^3.0.7+1
  intl_phone_field: ^3.2.0

  # State Management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1

  # Dependency Injection & Architecture Helpers
  get_it: ^9.2.0
  equatable: ^2.0.7
  dartz: ^0.10.1

  # App Info, Device, Updates & Utilities
  upgrader: ^12.3.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  easy_debounce: ^2.0.3
  internet_connection_checker_plus: ^2.9.1+2

  # WebView & External Links
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2

  # UI / Animations / Widgets
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  page_transition: ^2.2.1
  smooth_page_indicator: ^2.0.1
  carousel_slider: ^5.1.1
  fluttertoast: ^9.0.0
  flutter_rating_bar: ^4.0.1
  animate_do: ^4.2.0
  pin_code_fields: ^8.0.1
  calendar_date_picker2: ^2.0.1
  skeletonizer: ^2.1.2
  google_nav_bar: ^5.0.7
  easy_stepper: ^0.9.1
  voice_note_kit: ^1.3.3

  # Permissions, Files & Paths
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  file_picker: ^10.3.8
  flutter_image_compress: ^2.4.0
  path: ^1.9.1
  # image_picker: ^1.1.2

  # Local Storage / Secure Storage
  flutter_secure_storage: ^10.0.0

  # Networking & Realtime
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  http: ^1.6.0
  pusher_channels_flutter: ^2.6.0
  # talker_dio_logger: ^4.7.5

  # Firebase & Notifications
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0

  # Date & Time
  timezone: ^0.10.1

  # Map / Location (Optional)
  # map_location_picker: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints & Code Generation
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  # hive_generator: ^2.0.1

  # App Branding (Icons & Splash)
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/splash_android_12.png
  color: "#ffffff"
  image_dark: assets/images/splash_android_12.png
  color_dark: "#ffffff"
  android: true
  ios: true

  android_12:
    image: assets/images/splash_android_12.png
    color: "#ffffff"
    image_dark: assets/images/splash_android_12.png
    color_dark: "#ffffff"

# dart run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/translation/
    - assets/fonts/cairo/
    - assets/images/app_logo.png
    - assets/images/intro_1.png
    - assets/images/intro_2.png
    - assets/images/intro_3.png
    - assets/images/login.png
    - assets/images/splash_background.png

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
